COMPONENT=TempTestAppC
CFLAGS += -I/home/vadoz/tinyos-main/tos/lib/printf
#CFLAGS += -DNEW_PRINTF_SEMANTICS
CFLAGS += -DLOW_POWER_LISTENING


TINYOS_ROOT_DIR?=/home/vadoz/tinyos-main
include $(TINYOS_ROOT_DIR)/Makefile.include
